### PR TITLE
Make `importlib_metadata` optional on Python 3.10

### LINKED ISSUE #575: Make importlib_metadata optional on Python 3.10.
> That extra dependency will become optional again in Python 3.10 alpha 7.

Could it be marked as required only for Python < 3.10 in `setup.cfg`?

_Originally posted by @dotlambda in https://github.com/jaraco/keyring/issues/503#issuecomment-1134170726_

### PR DESCRIPTION
**Pull request by tal66**
Hi, I think this will close #575.

### CODE REVIEW

**Review by mitya57 — CHANGES_REQUESTED** [review]
You also need to update imports to use the standard library module if it's available, instead of the backport.

I.e. replace this
```python
import importlib_metadata as metadata
```

with something like this
```python
import sys

if sys.version_info >= (3, 10):
    from importlib import metadata
else:
    import importlib_metadata as metadata
```

**Comment by tal66** [comment]
closing this, since I see you gave the same task to another PR with the same change, submitted 2 days after this one.
no need to have us both do this

**Comment by mitya57** [comment]
I don't have a reason to prefer the other pull request over this one, or vice versa. I saw two similar pull requests, and left two similar comments.

The other pull request is still not ready yet — there are CI failures.

**Comment by tal66** [comment]
i'm sure with your guidance he can pull this off. illogical to let us both spend time on this just to reject one. plus i don’t like the encouragement to submit a pr that someone else already started – i’d never do that even when I know better. cheers

**Pull request closed without merging**
