### PR TITLE
Add gitignore

### PR DESCRIPTION
**Pull request by mindw**
upstream is in an odd state (7.0 commit is not part of master).

### CODE REVIEW

**Comment by jaraco** [comment]
I dislike these spammy .gitignore files. If the settings are something that apply globally, then they should exist globally, and not copied and separately managed in every project. The .gitignore for a project should reflect the project's specific behavior. I've rebased this commit onto the master, so it's there, even though I don't like it.

**Comment by mindw** [comment]
Sure. A minimal one will do?

**Comment by mindw** [comment]
Sorry about that. 

I'll keep this mind for any future pulls for your projects.

**Comment by jaraco** [comment]
No biggie. Just a pet peave.

**Pull request closed without merging**
