### PR TITLE
Support both kwallet and kwallet5 dcop interfaces

### PR DESCRIPTION
**Pull request by frispete**
Hi, first of all, thank you for this great package. 

I had been working on a PyQt3 to PyQt5 transition of an inhouse app, and was in need of a kwallet interface. Unfortunately, I need to support both kwallet variants. The attached PR does exactly that, in a transparent way, and answers some questions in the doc string, I asked myself, when started experimenting with keyring.

Hopefully, the PR is acceptable for you. It's carefully designed to just adding what was needed.
One thing, I'm not 100% confident is, that it is using the dcop ProxyObject over the runtime of of keyring, expecting, that the dcop session will survive over the full keyring session.

### CODE REVIEW

**Comment by frispete** [comment]
Follow up patch tries to deal with invalidated dbus sessions, as well as changing kwallets.

**Comment by jaraco** [comment]
Hey Frispete. Glad to have you bringing contributions. This change seems reasonable and acceptable, though I'll probably re-write it slightly to implement it as two different backends. I'm not all that familiar with the Linux backends, but I do have a question - have you tried the SecretService backend? My understanding is it is has broader support and might work in both of the cases you're describing.

**Comment by mitya57** [comment]
KWallet (still) does not support Secret Service :-(

**Comment by jaraco** [comment]
Okay. That explains it. Thanks @mitya57.

**Comment by jaraco** [comment]
@frispete: I've extracted a separate backend for each mode. Can you test with the latest head and let me know if it works in both environments?

**Comment by mitya57** [comment]
Now that we have this, you can probably drop the old KWallet backend from keyrings.alt.

**Comment by frispete** [comment]
Hi Jason, glad you liked it. Thanks for merging! Much appreciated. This way, keyring is able to support the majority of KDE installations out there.

**Comment by jaraco** [comment]
> drop the old KWallet backend from keyrings.alt

Good idea.

**Pull request merged**
