### PR TITLE
Fix plain emit with Anonymous Credentials #692

### PR DESCRIPTION
**Pull request by daaniam**

### CODE REVIEW

**Comment by Tommaso-FLYR** [comment]
thank you! This broke our CI :/

**Comment by daaniam** [comment]
@Tommaso-FLYR, do you have an estimated timeframe for when it might be fixed? We use it without a pinned version in a few Dockerfiles as a UV tool. Thank you.

**Comment by Tommaso-FLYR** [comment]
> @Tommaso-FLYR, do you have an estimated timeframe for when it might be fixed? We use it without a pinned version in a few Dockerfiles as a UV tool. Thank you.

well I'm not a maintainer here so I can't answer to that. However we probably have the same setup (dockerfile + uv)

This is how I fixed it:
```diff
- RUN uv pip install keyring keyrings.google-artifactregistry-auth && \
+ RUN uv pip install keyring==25.3.0 keyrings.google-artifactregistry-auth && \
    uv pip install --keyring-provider subprocess -r requirements.txt && \
    uv pip uninstall keyring keyrings.google-artifactregistry-auth
```

**Comment by jaraco** [comment]
Per #694, the issue also affects `_emit_json`. Since #695 addresses both concerns, I'm going to work from that one. Regardless, thanks for the contrib, as it re-enforces the approach proposed there.

**Pull request closed without merging**
